version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        env_file:
            - .env
        expose:
            - "9000"  # PHP-FPM inside Docker listens on 9000
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        container_name: laravel_nginx
        restart: unless-stopped
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.laravel.rule=Host(`yourdomain.com`)"  # Change to your domain or IP
            - "traefik.http.services.laravel.loadbalancer.server.port=80"
        depends_on:
            - app
        networks:
            - laravel
            - traefik  # Attach Nginx to the existing Traefik network

networks:
    laravel:
        driver: bridge
    traefik:  # Make sure Nginx connects to Traefik’s network
        external: true