# Define the build plan for Laravel
[build]
# Specify PHP and required extensions
plan = "php"
env = { NIXPACKS_PHP_ROOT_DIR = "/var/www/html/public", NIXPACKS_PHP_FALLBACK_PATH = "/index.php" }

# Install required PHP extensions
[variables]
NIXPACKS_PHP_EXTENSIONS = "pdo pdo_mysql mbstring tokenizer"

# Install composer dependencies
[phases.setup]
cmds = [
    "composer install",
]

# Migrate the database automatically (Optional)
#[phases.deploy]
#cmds = [
#    "php artisan migrate"
#]

# Define the start command for Laravel
[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
