[phases.setup]
# Use PHP 8.3 instead of the latest PHP version
nixPkgs = ["php83", "phpPackages.composer", "nginx", "nodejs", "yarn"]

[phases.build]
cmds = [
    "mkdir -p bootstrap/cache storage/framework/cache storage/framework/views storage/logs",
    "chmod -R 775 bootstrap/cache storage",
    "composer install --no-dev --optimize-autoloader",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache",
    "npm install && npm run build"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=8000"
