[phases.setup]
nixPkgs = ["php", "phpPackages.composer", "nginx", "php-fpm", "nodejs", "coreutils"]

[phases.build]
cmds = [
    "composer install",
    "php artisan config:clear",
    "php artisan route:clear",
    "php artisan view:clear",
    "php artisan cache:clear",
    "php artisan storage:link"
]

[start]
cmds = [
    "nginx -c /app/nginx.conf"
]
