[phases.setup]
nixPkgsVersion = "unstable"  # Use unstable to ensure compatibility
nixPkgs = [
    "php",
    "phpPackages.composer",  # reference composer correctly
    "nodejs",
    "yarn",
    "nginx",
    "postgresql",
    "mysql",
    "openssl",
    "sqlite"
]

cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm install",
    "npm run build"
]

[phases.build]
cmds = [
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache",
    "php artisan migrate --force"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT:-8000}"
