# nixpacks.toml - Nixpacks configuration for Laravel 11

[phases.setup]
# Install required system dependencies, PHP 8.2, and Composer
aptPkgs = [
    "git",
    "unzip",
    "curl",
    "libpng-dev",
    "libjpeg-dev",
    "libfreetype6-dev",
    "php8.2",
    "nodejs",
    "npm"
]

cmds = [
    "curl -sS https://getcomposer.org/installer | php",
    "mv composer.phar /usr/local/bin/composer"
]

[phases.build]
# Run all Laravel build commands inside the app directory
cmds = [
    "composer install --no-dev --prefer-dist --optimize-autoloader",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache",
    "php artisan storage:link"
]

[phases.start]
# Start Laravel inside the app directory
cmds = ["php artisan serve --host=0.0.0.0 --port=${PORT}"]

[plan]
# Define runtime environment
runtime = "php"

# Install required PHP extensions for Laravel 11
packages = [
    "php",
    "php-cli",
    "php-mbstring",
    "php-xml",
    "php-bcmath",
    "php-curl",
    "php-tokenizer",
    "php-zip",
    "php-fpm",
    "php-pdo",
    "php-mysql",
    "php-opcache",
    "php-gd"
]

# Include essential Laravel directories and files
include = [".env", "storage", "bootstrap/cache", "public"]
