[phases.setup]
nixPkgs = ["php", "composer", "nginx", "php-fpm", "nodejs", "coreutils"]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "php artisan config:clear",
    "php artisan route:clear",
    "php artisan view:clear",
    "php artisan cache:clear",
    "php artisan storage:link"
]

[start]
cmds = [
    "php artisan migrate --force",
    "php artisan queue:restart",
    "nginx -c /app/nginx.conf"
]
