version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            target: production  # Ensure we're building the correct stage
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./laravel-app:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini  # Ensure custom PHP config
        environment:
            - APP_ENV=production
            - APP_DEBUG=false
        networks:
            - laravel_network

    nginx:
        image: nginx:latest
        container_name: laravel_nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./laravel-app:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            app:
                condition: service_healthy  # Ensures Laravel app is ready before Nginx starts
        networks:
            - laravel_network

networks:
    laravel_network:
        driver: bridge
