# deploy/docker-compose.yml

version: '3.8'

services:
    laravel:
        restart: unless-stopped
        container_name: laravelapp
        build:
            context: ../
            dockerfile: ./deploy/Dockerfile
        volumes:
            - ../storage/app:/var/www/html/storage/app
        environment:
            APP_NAME: ${APP_NAME}
            APP_ENV: ${APP_ENV}
            APP_DEBUG: ${APP_DEBUG}
            APP_KEY: ${APP_KEY}
            APP_URL: ${APP_URL}
            DB_CONNECTION: mysql
            DB_HOST: database
            DB_PORT: 3306
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
        ports:
            - "8080:80"
        networks:
            - laravel-network
        depends_on:
            - database

    database:
        restart: unless-stopped
        image: mariadb:lts-jammy
        volumes:
            - v-database:/var/lib/mysql
        environment:
            MARIADB_DATABASE: ${DB_DATABASE}
            MARIADB_USER: ${DB_USERNAME}
            MARIADB_PASSWORD: ${DB_PASSWORD}
            MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        networks:
            - laravel-network

volumes:
    v-database:

networks:
    laravel-network:
        driver: bridge
