version: '3.8'

services:
    laravel:
        restart: unless-stopped
        container_name: laravelapp
        build:
            context: ../
            dockerfile: ./deploy/Dockerfile
        volumes:
            - ../storage/app:/var/www/html/storage/app
            - ../deploy/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
        environment:
            APP_NAME: ${APP_NAME}
            APP_ENV: ${APP_ENV}
            APP_DEBUG: ${APP_DEBUG}
            APP_KEY: ${APP_KEY}
            APP_VERSION: ${APP_VERSION}
            APP_URL: ${APP_URL}
            DB_CONNECTION: mysql
            DB_HOST: database
            DB_PORT: 3306
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            MAIL_MAILER: ${MAIL_MAILER}
            MAIL_HOST: ${MAIL_HOST}
            MAIL_PORT: ${MAIL_PORT}
            MAIL_USERNAME: ${MAIL_USERNAME}
            MAIL_PASSWORD: ${MAIL_PASSWORD}
            MAIL_ENCRYPTION: ${MAIL_ENCRYPTION}
            MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
            MAIL_FROM_NAME: ${MAIL_FROM_NAME}
        ports:
            - "9000:9000"
        networks:
            - n-laravel
        depends_on:
            - database
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.laravel.rule=Host(`portfolio-backendapi-qye4ze-112f47-46-202-140-198.traefik.me`)"
            - "traefik.http.services.laravel.loadbalancer.server.port=9000"

    nginx:
        image: nginx:latest
        container_name: nginx
        restart: unless-stopped
        volumes:
            - ../deploy/nginx.conf:/etc/nginx/conf.d/default.conf
            - ../storage/app:/var/www/html/storage/app
        ports:
            - "8080:80"
        networks:
            - n-laravel
        depends_on:
            - laravel

    database:
        restart: unless-stopped
        image: mariadb:lts-jammy
        volumes:
            - v-database:/var/lib/mysql
        environment:
            MARIADB_DATABASE: ${DB_DATABASE}
            MARIADB_USER: ${DB_USERNAME}
            MARIADB_PASSWORD: ${DB_PASSWORD}
            MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        networks:
            - n-laravel

volumes:
    v-database:

networks:
    n-laravel:
        driver: bridge
